---
language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head

sudo: false

matrix:
  include:
    - { rvm: 1.9.3, env: rack=1.4.0  }
    - { rvm: 1.8.7, env: tilt=master }
    - { rvm: 1.9.3, env: rack=master }
    - { rvm: 1.9.3, env: tilt=master }
  allow_failures:
    - env: tilt=master
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
